@InvenTrack_HostAddress = https://localhost:7019

GET {{InvenTrack_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{InvenTrack_HostAddress}}/api/product

###

POST {{InvenTrack_HostAddress}}/api/product
Content-Type: application/json

{
  "name": "HP Pavilion 15",
  "sku": "HP-LAP-006",
  "price": 58999.99,
  "stockQuantity": 25,
  "supplierId": 1,
  "supplier":{}
}

###

GET {{InvenTrack_HostAddress}}/api/supplier

###

POST {{InvenTrack_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "john_doe",
  "email": "john.doe@example.com",
  "password": "John@12345"
}

###

POST {{InvenTrack_HostAddress}}/api/auth/login
Content-Type: application/json

{
   "email": "john.doe@example.com",
  "password": "John@12345"
}

###

GET {{InvenTrack_HostAddress}}/api/user

###
