import { useEffect, useState } from "react";
import { Eye, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { productApi, supplierApi, getErrorMessage } from "../services/api";
import { useAuth } from "../context/AuthContext";
import Modal from "../components/Modal";
import Loading from "../components/Loading";
import EmptyState from "../components/EmptyState";

const money = new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2});

export default function Products(){
  const {isAdmin}=useAuth(); const navigate=useNavigate(); const [params]=useSearchParams();
  const [products,setProducts]=useState([]),[suppliers,setSuppliers]=useState([]),[search,setSearch]=useState(""),[supplierId,setSupplierId]=useState(""),[lowOnly,setLowOnly]=useState(params.get("lowStock")==="10"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[editing,setEditing]=useState(null),[deleting,setDeleting]=useState(null);
  const load=async()=>{try{setLoading(true);setError("");const [p,s]=await Promise.all([productApi.list({search:search||undefined,supplierId:supplierId||undefined,lowStock:lowOnly?10:undefined}),supplierApi.list()]);setProducts(p.data);setSuppliers(s.data)}catch(e){setError(getErrorMessage(e))}finally{setLoading(false)}};
  useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[search,supplierId,lowOnly]);
  const remove=async()=>{try{await productApi.remove(deleting.id);setDeleting(null);load()}catch(e){setError(getErrorMessage(e))}};
  return <div>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="page-title">Products</h1><p className="mt-1 text-sm text-slate">Catalog, pricing and current stock levels.</p></div>{isAdmin&&<button onClick={()=>setEditing({})} className="btn-primary"><Plus size={17}/> Add product</button>}</div>
    {error&&<div className="mt-5 rounded-lg bg-red/5 p-3 text-sm text-red">{error}</div>}
    <div className="card mt-6 p-4"><div className="grid gap-3 md:grid-cols-[1fr_220px_auto]"><div className="relative"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate/60"/><input className="input pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name or SKU"/></div><select className="input" value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">All suppliers</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><label className="flex cursor-pointer items-center gap-2 rounded-lg border border-line px-3.5 text-sm font-medium"><input type="checkbox" checked={lowOnly} onChange={e=>setLowOnly(e.target.checked)} className="accent-teal"/> Low stock</label></div></div>
    <div className="card mt-4 overflow-hidden">
      {loading?<Loading/>:products.length===0?<EmptyState title="No products found" description="Try changing your search or filters."/>:<div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left"><thead className="border-b border-line bg-surface text-xs uppercase tracking-wide text-slate"><tr><th className="px-5 py-3.5 font-semibold">Product</th><th className="px-5 py-3.5 font-semibold">SKU</th><th className="px-5 py-3.5 font-semibold">Supplier</th><th className="px-5 py-3.5 font-semibold">Price</th><th className="px-5 py-3.5 font-semibold">Stock</th><th className="px-5 py-3.5 text-right font-semibold">Actions</th></tr></thead><tbody className="divide-y divide-line">{products.map(p=><tr key={p.id} className="hover:bg-surface/70"><td className="px-5 py-4"><button onClick={()=>navigate(`/products/${p.id}`)} className="text-left font-semibold hover:text-teal">{p.name}</button></td><td className="px-5 py-4 text-sm text-slate">{p.sku}</td><td className="px-5 py-4 text-sm">{p.supplierName}</td><td className="px-5 py-4 text-sm font-medium">{money.format(p.price)}</td><td className="px-5 py-4"><StockBadge value={p.stockQuantity}/></td><td className="px-5 py-4"><div className="flex justify-end gap-1">{<button className="rounded-lg p-2 text-slate hover:bg-surface hover:text-teal" title="View" onClick={()=>navigate(`/products/${p.id}`)}><Eye size={17}/></button>}{isAdmin&&<><button className="rounded-lg p-2 text-slate hover:bg-surface hover:text-teal" title="Edit" onClick={()=>setEditing(p)}><Pencil size={17}/></button><button className="rounded-lg p-2 text-slate hover:bg-red/5 hover:text-red" title="Delete" onClick={()=>setDeleting(p)}><Trash2 size={17}/></button></>}</div></td></tr>)}</tbody></table></div>}
    </div>
    <Modal open={editing!==null} onClose={()=>setEditing(null)} title={editing?.id?"Edit product":"Add product"}><ProductForm product={editing} suppliers={suppliers} onDone={()=>{setEditing(null);load()}}/></Modal>
    <Modal open={!!deleting} onClose={()=>setDeleting(null)} title="Delete product"><div className="p-5"><p className="text-sm text-slate">Delete <strong className="text-ink">{deleting?.name}</strong>? This action cannot be undone.</p><div className="mt-6 flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setDeleting(null)}>Cancel</button><button className="btn-danger" onClick={remove}>Delete</button></div></div></Modal>
  </div>;
}
function StockBadge({value}){const danger=value<=10;return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${danger?"bg-amber/10 text-amber":"bg-teal/10 text-teal"}`}>{value} units</span>}
function ProductForm({product,suppliers,onDone}){const [form,setForm]=useState({name:product?.name||"",sku:product?.sku||"",price:product?.price??"",stockQuantity:product?.stockQuantity??"",supplierId:product?.supplierId||""});const [error,setError]=useState("");const [saving,setSaving]=useState(false);
 const submit=async(e)=>{e.preventDefault();setError("");if(!form.name.trim()||!form.sku.trim()||!form.supplierId)return setError("Name, SKU and supplier are required.");if(Number(form.price)<0||Number(form.stockQuantity)<0)return setError("Price and stock cannot be negative.");try{setSaving(true);const payload={name:form.name.trim(),sku:form.sku.trim(),price:Number(form.price),stockQuantity:Number(form.stockQuantity),supplierId:Number(form.supplierId)};product?.id?await productApi.update(product.id,payload):await productApi.create(payload);onDone()}catch(e){setError(getErrorMessage(e))}finally{setSaving(false)}};
 return <form onSubmit={submit} className="p-5"><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><label className="label">Product name</label><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label className="label">SKU</label><input className="input" value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/></div><div><label className="label">Supplier</label><select className="input" value={form.supplierId} onChange={e=>setForm({...form,supplierId:e.target.value})}><option value="">Select supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div><label className="label">Price (₹)</label><input className="input" type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></div><div><label className="label">Stock quantity</label><input className="input" type="number" min="0" step="1" value={form.stockQuantity} onChange={e=>setForm({...form,stockQuantity:e.target.value})}/></div></div>{error&&<div className="mt-4 rounded-lg bg-red/5 p-3 text-sm text-red">{error}</div>}<div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={onDone}>Cancel</button><button disabled={saving} className="btn-primary">{saving?"Saving...":"Save product"}</button></div></form> }