import { useEffect, useState } from "react";
import { Pencil, Plus, Search, Truck } from "lucide-react";
import { supplierApi, getErrorMessage } from "../services/api";
import Modal from "../components/Modal";
import Loading from "../components/Loading";
import EmptyState from "../components/EmptyState";

export default function Suppliers(){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[editing,setEditing]=useState(null);
 const load=()=>{setLoading(true);supplierApi.list().then(r=>setItems(r.data)).catch(e=>setError(getErrorMessage(e))).finally(()=>setLoading(false))};
 useEffect(load,[]);
 const filtered=items.filter(x=>`${x.name} ${x.email||""} ${x.phone||""}`.toLowerCase().includes(query.toLowerCase()));
 return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="page-title">Suppliers</h1><p className="mt-1 text-sm text-slate">Keep vendor contacts clean and linked to your products.</p></div><button className="btn-primary" onClick={()=>setEditing({})}><Plus size={17}/> Add supplier</button></div>
 {error&&<div className="mt-5 rounded-lg bg-red/5 p-3 text-sm text-red">{error}</div>}
 <div className="card mt-6 p-4"><div className="relative max-w-md"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate/60"/><input className="input pl-9" placeholder="Search suppliers" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>
 <div className="card mt-4 overflow-hidden">{loading?<Loading/>:filtered.length===0?<EmptyState title="No suppliers found"/>:<div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead className="border-b border-line bg-surface text-xs uppercase tracking-wide text-slate"><tr><th className="px-5 py-3.5">Supplier</th><th className="px-5 py-3.5">Email</th><th className="px-5 py-3.5">Phone</th><th className="px-5 py-3.5">Address</th><th className="px-5 py-3.5 text-right">Actions</th></tr></thead><tbody className="divide-y divide-line">{filtered.map(s=><tr key={s.id} className="hover:bg-surface/60"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="rounded-lg bg-teal/10 p-2 text-teal"><Truck size={17}/></div><div className="font-semibold">{s.name}</div></div></td><td className="px-5 py-4 text-sm text-slate">{s.email||"—"}</td><td className="px-5 py-4 text-sm">{s.phone||"—"}</td><td className="max-w-xs truncate px-5 py-4 text-sm text-slate">{s.address||"—"}</td><td className="px-5 py-4 text-right"><button className="rounded-lg p-2 text-slate hover:bg-surface hover:text-teal" onClick={()=>setEditing(s)}><Pencil size={17}/></button></td></tr>)}</tbody></table></div>}</div>
 <Modal open={editing!==null} onClose={()=>setEditing(null)} title={editing?.id?"Edit supplier":"Add supplier"}><SupplierForm supplier={editing} onDone={()=>{setEditing(null);load()}}/></Modal></div>;
}
function SupplierForm({supplier,onDone}){const [form,setForm]=useState({name:supplier?.name||"",email:supplier?.email||"",phone:supplier?.phone||"",address:supplier?.address||""}),[error,setError]=useState(""),[saving,setSaving]=useState(false);const submit=async(e)=>{e.preventDefault();if(!form.name.trim())return setError("Supplier name is required.");try{setSaving(true);const p={name:form.name.trim(),email:form.email.trim()||null,phone:form.phone.trim()||null,address:form.address.trim()||null};supplier?.id?await supplierApi.update(supplier.id,p):await supplierApi.create(p);onDone()}catch(e){setError(getErrorMessage(e))}finally{setSaving(false)}};return <form className="p-5" onSubmit={submit}><div className="space-y-4"><div><label className="label">Supplier name</label><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Email</label><input className="input" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><label className="label">Phone</label><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div></div><div><label className="label">Address</label><textarea className="input min-h-24 resize-y" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></div></div>{error&&<div className="mt-4 rounded-lg bg-red/5 p-3 text-sm text-red">{error}</div>}<div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={onDone}>Cancel</button><button disabled={saving} className="btn-primary">{saving?"Saving...":"Save supplier"}</button></div></form>}